### ISSUE TITLE
Spark AR 93.1

### ISSUE THREAD

**Issue by orenmm** [pofulu/sparkar-smoother#1]
**JavaScript error: Error: EACCES: permission denied, copyfile '.....**
any idea why I'm getting this? I am trying to locate the lips location but in Spark AR natively it isn't possible hence I use your script.

**Comment by pofulu** [comment]
It's not about this repo.
Do you use Windows or macOS? I found this post in main group, maybe it helps.

https://www.facebook.com/groups/SparkARcommunity/permalink/851005618644815/
